#!/bin/bash

echo "Here is daemonize"

cleanup() {
  kill -s SIGTERM $!                                                     
  exit 0
}

trap cleanup SIGINT SIGTERM

while sleep 1; do
  wait $!
  echo "deamonize"
done